---
- name: configuration d'apache 
  blockinfile:
    path: /etc/httpd/conf/httpd.conf 
    insertafter: EOF
    content: |
         Listen {{ port }} 
         <VirtualHost 192.168.0.15:{{ port }}>
         DocumentRoot "/var/www/html"
         </VirtualHost>
    backup: yes 
